# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "7.0.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "9.1.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      puppet_version: ">= 6.0.0"
    dockerinstall:
      repo: "aursu/dockerinstall"
      ref: "0.16.1"
    firewalld:
      repo: "puppet/firewalld"
      ref: "4.5.1"
    kmod:
      repo: "puppet/kmod"
      ref: "4.0.0"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.15.0"
    selinux:
      repo: "puppet/selinux"
      ref: "4.0.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "9.3.0"
    sysctl:
      repo: "thias/sysctl"
      ref: "1.0.7"
    systemd:
      repo: "puppet/systemd"
      ref: "6.0.0"
    yum:
      repo: "puppet/yum"
      ref: "7.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      puppet_version: ">= 6.0.0"
    bsys:
      repo: aursu/bsys
      ref: 0.3.1
    tlsinfo:
      repo: aursu/tlsinfo
      ref: 0.5.0
