# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "4.4.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "8.3.0"
    augeas_core:
      repo: "puppetlabs/augeas_core"
      puppet_version: ">= 6.0.0"
    dockerinstall:
      repo: "aursu/dockerinstall"
      ref: "0.13.1"
    firewalld:
      repo: "puppet/firewalld"
      ref: "4.3.0"
    kmod:
      repo: "puppet/kmod"
      ref: "3.1.1"
    puppet_agent:
      repo: "puppetlabs/puppet_agent"
      ref: "4.0.0"
    selinux:
      repo: "puppet/selinux"
      ref: "3.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.1.0"
    sysctl:
      repo: "thias/sysctl"
      ref: "1.0.7"
    systemd:
      repo: "puppet/systemd"
      ref: "3.8.0"
    yum:
      repo: "puppet/yum"
      ref: "5.4.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      puppet_version: ">= 6.0.0"
  repositories:
    tlsinfo:
      repo: https://github.com/aursu/puppet-tlsinfo.git
